#############################################################################
# Makefile for building: nc100.app/Contents/MacOS/nc100
# Generated by qmake (3.1) (Qt 6.2.0)
# Project:  nc100.pro
# Template: app
# Command: /Users/petrvanek/Qt/6.2.0/macos/bin/qmake -o nc100.xcodeproj/project.pbxproj nc100.pro -spec macx-xcode
#############################################################################

MAKEFILE      = project.pbxproj

EQ            = =

QMAKE    = /Users/petrvanek/Qt/6.2.0/macos/bin/qmake
nc100.xcodeproj/project.pbxproj: nc100.pro /Users/petrvanek/Qt/6.2.0/macos/mkspecs/macx-clang/qmake.conf /Users/petrvanek/Qt/6.2.0/macos/mkspecs/features/spec_pre.prf \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/features/device_config.prf \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/common/unix.conf \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/common/mac.conf \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/common/macx.conf \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/common/sanitize.conf \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/common/gcc-base.conf \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/common/gcc-base-mac.conf \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/common/clang.conf \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/common/clang-mac.conf \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/qconfig.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_ext_freetype.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_ext_libpng.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_3danimation.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_3danimation_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_3dcore.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_3dextras.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_3dextras_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_3dinput.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_3dlogic.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_3dquick.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_3dquickextras.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_3drender.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_3drender_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_bluetooth.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_charts.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_charts_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_chartsqml.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_chartsqml_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_core.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_core5compat.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_core5compat_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_core_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_datavisualization.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_dbus.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_dbus_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_designer.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_designer_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_fb_support_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_gui.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_help.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_help_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_labsanimation.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_labssettings.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_labssettings_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_labssharedimage.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_linguist.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_linguist_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_multimedia.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_network.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_network_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_networkauth.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_networkauth_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_nfc.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_nfc_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_opengl.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_openglwidgets.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_positioning.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_positioning_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_positioningquick.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_qml.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_qmlcore.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_qmlcore_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_qmldom_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_qmlmodels.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quick.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quick3d.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quick3d_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quick3deffects.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quick3deffects_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quick3dparticles.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quick3dutils.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quicklayouts.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quicktimeline.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_remoteobjects.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_remoteobjectsqml.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_repparser.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_repparser_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_scxml.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_scxml_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_scxmlqml.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_scxmlqml_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_sensors.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_sensors_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_sensorsquick.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_sensorsquick_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_serialbus.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_serialbus_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_serialport.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_serialport_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_shadertools.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_shadertools_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_sql.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_statemachine.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_statemachine_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_statemachineqml.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_statemachineqml_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_svg.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_svgwidgets.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_testlib.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_tools_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_uiplugin.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_uitools.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_webchannel.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_webenginecore.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_webenginequick.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_webenginequick_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_webenginequickdelegatesqml_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_websockets.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_websockets_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_webview.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_webview_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_webviewquick.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_webviewquick_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_widgets.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_xml.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/features/qt_functions.prf \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/features/qt_config.prf \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/macx-clang/qmake.conf \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/macx-xcode/qmake.conf \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/features/exclusive_builds.prf \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/features/mac/sdk.prf \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/features/toolchain.prf \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/features/mac/toolchain.prf \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/features/default_pre.prf \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/features/mac/default_pre.prf \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/features/resolve_config.prf \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/features/default_post.prf \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/features/mac/default_post.prf \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/features/mac/objective_c.prf \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/features/mac/mac.prf \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/features/warn_on.prf \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/features/qt.prf \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/features/resources_functions.prf \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/features/resources.prf \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/features/moc.prf \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/features/unix/opengl.prf \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/features/uic.prf \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/features/unix/thread.prf \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/features/qmake_use.prf \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/features/file_copies.prf \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/features/mac/rez.prf \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/features/mac/asset_catalogs.prf \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/features/testcase_targets.prf \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/features/exceptions.prf \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/features/yacc.prf \
		/Users/petrvanek/Qt/6.2.0/macos/mkspecs/features/lex.prf \
		nc100.pro \
		/Users/petrvanek/Qt/6.2.0/macos/lib/QtWidgets.framework/Resources/QtWidgets.prl \
		/Users/petrvanek/Qt/6.2.0/macos/lib/QtGui.framework/Resources/QtGui.prl \
		/Users/petrvanek/Qt/6.2.0/macos/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o nc100.xcodeproj/project.pbxproj nc100.pro -spec macx-xcode
	@echo 'warning: Xcode project has been regenerated, custom settings have been lost. Use CONFIG+=no_autoqmake to prevent this behavior in the future, at the cost of requiring manual project change tracking.'
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/features/spec_pre.prf:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/features/device_config.prf:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/common/unix.conf:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/common/mac.conf:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/common/macx.conf:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/common/sanitize.conf:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/common/gcc-base.conf:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/common/gcc-base-mac.conf:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/common/clang.conf:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/common/clang-mac.conf:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/qconfig.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_ext_freetype.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_ext_libpng.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_3danimation.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_3danimation_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_3dcore.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_3dcore_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_3dextras.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_3dextras_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_3dinput.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_3dinput_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_3dlogic.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_3dlogic_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_3dquick.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_3dquick_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_3dquickanimation.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_3dquickextras.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_3dquickinput.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_3dquickrender.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_3drender.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_3drender_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_bluetooth.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_bluetooth_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_bodymovin_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_charts.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_charts_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_chartsqml.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_chartsqml_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_concurrent.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_concurrent_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_core.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_core5compat.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_core5compat_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_core_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_datavisualization.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_datavisualization_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_dbus.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_dbus_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_designer.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_designer_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_designercomponents_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_fb_support_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_gui.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_gui_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_help.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_help_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_labsanimation.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_labsanimation_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_labssettings.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_labssettings_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_labssharedimage.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_linguist.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_linguist_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_multimedia.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_multimedia_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_multimediaquick_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_network.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_network_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_networkauth.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_networkauth_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_nfc.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_nfc_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_opengl.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_opengl_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_openglwidgets.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_positioning.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_positioning_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_positioningquick.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_positioningquick_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_printsupport.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_printsupport_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_qml.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_qml_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_qmlcore.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_qmlcore_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_qmldebug_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_qmldom_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_qmlmodels.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_qmltest.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_qmltest_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quick.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quick3d.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quick3d_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quick3dassetimport.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quick3dassetutils.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quick3dassetutils_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quick3deffects.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quick3deffects_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quick3dhelpers.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quick3dhelpers_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quick3diblbaker.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quick3diblbaker_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quick3dparticles.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quick3dparticles_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quick3druntimerender.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quick3dutils.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quick3dutils_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quick_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quickcontrols2.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quickdialogs2.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quicklayouts.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quickparticles_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quickshapes_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quicktemplates2.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quicktimeline.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quicktimeline_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quickwidgets.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_remoteobjects.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_remoteobjectsqml.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_repparser.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_repparser_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_scxml.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_scxml_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_scxmlqml.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_scxmlqml_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_sensors.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_sensors_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_sensorsquick.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_sensorsquick_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_serialbus.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_serialbus_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_serialport.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_serialport_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_shadertools.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_shadertools_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_sql.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_sql_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_statemachine.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_statemachine_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_statemachineqml.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_statemachineqml_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_svg.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_svg_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_svgwidgets.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_testlib.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_testlib_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_tools_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_uiplugin.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_uitools.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_uitools_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_webchannel.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_webchannel_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_webenginecore.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_webenginecore_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_webenginequick.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_webenginequick_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_webenginequickdelegatesqml_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_webenginewidgets.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_websockets.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_websockets_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_webview.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_webview_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_webviewquick.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_webviewquick_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_widgets.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_widgets_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_xml.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/modules/qt_lib_xml_private.pri:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/features/qt_functions.prf:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/features/qt_config.prf:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/macx-clang/qmake.conf:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/macx-xcode/qmake.conf:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/features/spec_post.prf:
.qmake.stash:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/features/exclusive_builds.prf:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/features/mac/sdk.prf:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/features/toolchain.prf:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/features/mac/toolchain.prf:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/features/default_pre.prf:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/features/mac/default_pre.prf:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/features/resolve_config.prf:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/features/default_post.prf:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/features/mac/default_post.prf:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/features/mac/objective_c.prf:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/features/mac/mac.prf:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/features/warn_on.prf:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/features/qt.prf:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/features/resources_functions.prf:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/features/resources.prf:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/features/moc.prf:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/features/unix/opengl.prf:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/features/uic.prf:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/features/unix/thread.prf:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/features/qmake_use.prf:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/features/file_copies.prf:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/features/mac/rez.prf:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/features/mac/asset_catalogs.prf:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/features/testcase_targets.prf:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/features/exceptions.prf:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/features/yacc.prf:
/Users/petrvanek/Qt/6.2.0/macos/mkspecs/features/lex.prf:
nc100.pro:
/Users/petrvanek/Qt/6.2.0/macos/lib/QtWidgets.framework/Resources/QtWidgets.prl:
/Users/petrvanek/Qt/6.2.0/macos/lib/QtGui.framework/Resources/QtGui.prl:
/Users/petrvanek/Qt/6.2.0/macos/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o nc100.xcodeproj/project.pbxproj nc100.pro -spec macx-xcode

qmake_all: FORCE

